### ISSUE TITLE
moviepy

### ISSUE THREAD

**Issue by nevze** [upekshaip/tg-ytdlp-bot#2]
Traceback (most recent call last):
  File "//magic.py", line 13, in <module>
    from moviepy.editor import VideoFileClip
ModuleNotFoundError: No module named 'moviepy.editor'

**Comment by upekshaip** [comment]
> Traceback (most recent call last): File "//magic.py", line 13, in from moviepy.editor import VideoFileClip ModuleNotFoundError: No module named 'moviepy.editor'

**Comment by upekshaip** [comment]
Repo needs to update a little. I'll update it!

**Comment by chelaxian** [comment]
same error. but to fix it you can change `moviepy` in `requirements.txt` to `moviepy==1.0.3`
